<?php

/**
 * @file
 * Contains radicati_social.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\NodeType;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function radicati_social_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the radicati_social module.
        case "help.page.radicati_social":
            $output = "";
            $output .= "<h3>" . t("About") . "</h3>";
            $output .=
                "<p>" . t("Provides a simple social sharing block.") . "</p>";
            $output .= "</br>";
            $output .= "<h3>" . t("How-to") . "</h3>";
             $output .=
                "<p>" . t("Create a new custom block of the Social Sharing type, and place it where ever you need a social sharing block.") . "</p>";
            return $output;

        default:
    }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function radicati_social_theme_suggestions_field_alter(
    &$suggestions,
    $variables
) {
    $name = $variables["element"]["#field_name"];
    if ($name == "field_social_sharing_options") {
        $sanitized_view_mode = strtr(
            $variables["element"]["#view_mode"],
            ".",
            "_",
        );

        $suggestions[] = "field__radicati__" . $name;
        $suggestions[] =
            "field__radicati__" . $name . "__" . $sanitized_view_mode;
    }

    // $type = $entity->getType();
    // $names = [];

    // if (in_array($type, $names)) {
    //     //$suggestions[] = 'paragraph__radicati';
    //     $suggestions[] = "paragraph__radicati__" . $type;
    //     $suggestions[] =
    //         "paragraph__radicati__" . $type . "__" . $sanitized_view_mode;
    // }
}

/**
 * Implements hook_theme().
 */
function radicati_social_theme() {
    return [
      'radicati_social__share_button' => [
        'variables' => [
          'url' => NULL,
          'use_button' => NULL,
          'machine_name' => NULL,
          'label' => NULL,
          'service_name' => NULL,
          'icon_class' => NULL,
          'attributes' => NULL,
        ],
      ],
      'radicati_social__share_buttons' => [
        'variables' => [
          'label' => NULL,
          'buttons' => NULL,
        ],
      ],
    ];
}


/**
 * This makes the social sharing widget available on the node display tab.
 *
 * @return array
 */
function radicati_social_entity_extra_field_info() {
  $extra = [];
  $description = t('Social Sharing Widget, configured at /admin/config/services/radicati_social');

  foreach(NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->id()]['display']['social_widget'] = [
      'label' => t('Radicati Social Sharing'),
      'description' => $description,
      'weight' => 0,
      'visible' => FALSE,
    ];
  }

  return $extra;
}

function radicati_social_node_view(array &$build, EntityInterface $entity,
                                   EntityViewDisplayInterface $display, $view_mode) {
  if($display->getComponent('social_widget')) {
    $build['social_widget'] = _prepare_share_buttons();
  }
}

function _prepare_share_buttons() {
  $config = \Drupal::config('radicati_social.settings');
  $services = _radicati_social_get_services();

  $buttons = [];
  foreach($services as $key => $service) {
    $url = $service['url'];

    $path = \Drupal\Core\Url::fromRoute('<current>', [], ['absolute'=>TRUE])->toString();

    // Replace the {URL} placeholder in $url with the $path
    $url = str_replace('{URL}', $path, $url);

    $useButton = in_array($key, ['copy']);

    $buttons[] = [
      '#theme' => 'radicati_social__share_button',
      '#machine_name' => $key,
      '#use_button' => $useButton,
      '#url' => $url,
      '#label' => $service['label'],
      '#service_name' => $service['service_name'],
      '#icon_class' => $service['class'],
      '#attributes' => [
        'class' => [
          'rshare-button',
          'rshare-button--' . $key,
        ],
      ],
    ];
  }

  // Now render the sharing widget with the buttons using the
  // radicati_social__share_buttons defined above.
  $build = [
    '#theme' => 'radicati_social__share_buttons',
    '#label' => $config->get('label'),
    '#buttons' => $buttons,
    '#attached' => [
      'library' => [
        'radicati_social/popup',
      ],
    ],
  ];

  return $build;
}

/**
 * Loads the social services config and merges in the available_services to get the
 * share url and the service label. Returns an array that can be used to render
 * the social sharing buttons.
 */
function _radicati_social_get_services() {
  $config = \Drupal::config('radicati_social.settings');
  $services = $config->get('services');
  $available_services = $config->get('available_services');

  $output = [];

  foreach($services as $key => $service) {
    if($service['enabled'] == TRUE) {
      $output[$key] = $service;
      $output[$key]['url'] = $available_services[$key]['path'];
      $output[$key]['label'] = $available_services[$key]['label'];
    }

  }

  return $output;
}